sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run build-prod
deploy:
  provider: script
  script: bash ./deploy/git-config.sh && npm run deploy
  skip_cleanup: true
  on:
    branch: dev
